apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply the base manifests FIRST: kubectl apply -k k8s/base/
# Then apply this strategy: kubectl apply -k k8s/ab-testing/
namespace: aceest
resources:
  - variant-a.yaml
  - variant-b.yaml
  - ingress-ab.yaml
